[GLOBAL]
colors = true
plugins = ["hdrhistogram"]

print_stacktrace = true

[stats]
log = true

[test]
use_coverage = false

[coverage-py]
report = ["xml"]
global_report = true

[pytest]
args = ["-vv", "--no-header"]

[oci]
rootless = true
uid_map = []
gid_map = []


[umoci]
log = "debug"
