[GLOBAL]
colors = true
plugins = ["hdrhistogram"]
process_execution_local_parallelism = 1
rule_threads_core = 1
print_stacktrace = true

[stats]
log = true

[test]
use_coverage = false

[coverage-py]
report = ["xml"]
global_report = true

[pytest]
args = ["-vv", "--no-header"]

[oci]
rootless = false
uid_map = []
gid_map = []


[umoci]
log = "debug"
