[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["pants_backend_oci", "pants_backend_mdbook", "pants_backend_kustomize", "pants_backend_k8s", "pants_backend_secrets", "pants_backend_bitwarden"]

default_section = "THIRDPARTY"

[tool.black]
line-length = 110
preview = true

[tool.ruff]
line-length = 110
