apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome
  labels:
    app: welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - image: pause
        name: welcome
        volumeMounts:
        - name: config
          mountPath: /www/assets/config.yml
          subPath: config.yaml

      volumes:
      - name: config
        configMap:
          name: config
