apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: welcome

resources:
- deployment.yaml
- service.yaml

images:
  - name: pause
    newName: harbor.sbg.dev/test/pants-plugin-oci-example
    digest: //examples/oci:oci
