
on:
  pull_request:
jobs:
  check_cores:
    runs-on: ["ubuntu-latest"]
    steps:
    - name: Get the number of CPUs that the current process has access to.
      id: cpus

      run: |
        from os import environ, sched_getaffinity

        affinity = sched_getaffinity(0)
        num_cpus = len(affinity)
        output_file = environ["GITHUB_OUTPUT"]
        with open(output_file, "a", encoding="utf-8") as output_stream:
            output_stream.write(f"count={num_cpus}\n")
        print("number of cores", affinity, num_cpus)
        print(os.cpu_count())
      shell: python
