name: Python application

on:
  push:
    branches: [ "main" ]

  pull_request:

permissions:
  contents: read

env:
  PANTS_PANTSD: False

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        pants-version: ["2.14.0", "2.15.0", "2.16.0a0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Tell Pants to use Python 3.9
      run: |
        echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_VERSION=${{ matrix.pants-version }}" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==3.9.*']" >> $GITHUB_ENV

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-test-py3.9-pants${{ matrix.pants-version }}
        named-caches-hash: ${{ hashFiles('pants-plugins/lock.txt') }}

    - name: Test everything
      run: |
        ./get-pants.sh
        pants generate-lockfiles --resolve=pants-plugins
        pants test ::

  package:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        pants-version: ["2.14.0", "2.15.0", "2.16.0a0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Tell Pants to use Python 3.9
      run: |
        echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==3.9.*']" >> $GITHUB_ENV
        echo "PANTS_VERSION=${{ matrix.pants-version }}" >> $GITHUB_ENV

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-test-py3.9-pants${{ matrix.pants-version }}
        named-caches-hash: ${{ hashFiles('pants-plugins/lock.txt') }}

    - name: Package all targets
      run: |
        ./get-pants.sh
        pants package ::

  check-and-lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Tell Pants to use Python 3.9
      run: 'echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==3.9.*'']" >> $GITHUB_ENV
        '
    - name: Run linters on all targets
      run: |
        ./get-pants.sh
        pants update-build-files --check lint check ::

  validate-tailor:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Tell Pants to use Python 3.9
      run: 'echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==3.9.*'']" >> $GITHUB_ENV
        '
    - name: Validate that tailor files are up to date
      run: |
        ./get-pants.sh
        pants tailor --check ::
