name: Python application

on:
  push:
    branches: [ "main" ]

  pull_request:

permissions:
  contents: read

env:
  PANTS_PANTSD: False

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        pants-version: ["2.15.0", "2.16.0", "2.17.0rc1"]

    env:
       PANTS_BACKEND_PACKAGES: '-["pants.backend.experimental.python.lint.ruff"]'
       PANTS_VERIFY_CONFIG: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Tell Pants to use Python 3.9
      run: |
        echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_VERSION=${{ matrix.pants-version }}" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==3.9.*']" >> $GITHUB_ENV

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache1-test-py3.9-pants${{ matrix.pants-version }}
        named-caches-hash: ${{ hashFiles('pants-plugins/*.lock') }}

    - name: Test everything
      run: |
        ./get-pants.sh
        sudo sh -c 'echo "runner:100000:65536" > /etc/subuid'
        sudo sh -c 'echo "runner:100000:65536" > /etc/subgid'
        /home/runner/bin/pants test ::

  package:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        pants-version: ["2.15.0", "2.16.0", "2.17.0rc1"]

    env:
       PANTS_BACKEND_PACKAGES: '-["pants.backend.experimental.python.lint.ruff"]'
       PANTS_VERIFY_CONFIG: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Tell Pants to use Python 3.9
      run: |
        # echo "PY=python3.9" >> $GITHUB_ENV
        # echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=['==3.9.*']" >> $GITHUB_ENV
        echo "PANTS_VERSION=${{ matrix.pants-version }}" >> $GITHUB_ENV

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache1-package-py3.9-pants${{ matrix.pants-version }}
        named-caches-hash: ${{ hashFiles('pants-plugins/*.lock') }}

    - name: Package all targets
      run: |
        ./get-pants.sh
        id
        id -u
        id -g
        sudo sh -c 'echo "runner:100000:65536" > /etc/subuid'
        sudo sh -c 'echo "runner:100000:65536" > /etc/subgid'
        docker run --rm --cap-drop all --cap-add CAP_SETGID ubuntu:20.04 cat /proc/self/gid_map
        docker run --rm --cap-drop all --cap-add CAP_SETUID ubuntu:20.04 cat /proc/self/uid_map

        /home/runner/bin/pants package ::

  check-and-lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Tell Pants to use Python 3.9
      run: 'echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==3.9.*'']" >> $GITHUB_ENV
        '
    - name: Run linters on all targets
      run: |
        ./get-pants.sh
        /home/runner/bin/pants update-build-files --check lint check ::

  validate-tailor:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Tell Pants to use Python 3.9
      run: 'echo "PY=python3.9" >> $GITHUB_ENV
        echo "PANTS_PYTHON_INTERPRETER_CONSTRAINTS=[''==3.9.*'']" >> $GITHUB_ENV
        '
    - name: Validate that tailor files are up to date
      run: |
        ./get-pants.sh
        /home/runner/bin/pants tailor --check ::
